languages:
  C: true
  C++: true
  JavaScript: true
  XML: true
  Python: true
  csharp: true
  HTML: true
  shell script: true
  CSS: true
  Java: true
    solutions:
    UITests\userAuth.UITests.sln
    Droid\userAuth.Droid.sln
  
  
